language: python
python:
  - "3.2"
  - "3.3"
#  - "3.4"
before_script:
  - pip install -r test_requirements.txt --use-mirrors
script:
  - py.test -v --cov meters --cov-report term-missing #--pep8 meters
after_success:
  - coveralls --verbose
deploy:
  provider: pypi
  user: mdevaev
  password:
    secure: b5AUhaEjApP4XAH0aODUwoc6+aNvEX4zhkGadIBqYsZq7XVHVrmAvqIhrAOTXrSAX0KjOWVflsaeWuWoS4Pp/ocabndTfzSWZaXpIEws4QdCP3f3ST/RXcvdlznA8TTH7gHt4fGveQAuhhxlYceVcFME1WPrAtPfhExReetujsw=
  on:
    tags: true
