language: python
python:
  - "3.2"
  - "3.3"
#  - "3.4"
before_script:
  - pip install -r test_requirements.txt --use-mirrors
script:
  - py.test -v --cov meters --cov-report term-missing #--pep8 meters
after_success:
  - coveralls --verbose
deploy:
  provider: pypi
  user: mdevaev
  password:
    secure: "UIeIc82q2DZPA1U2wQE5qt5kA5zqbanyEZdIxx32vnjitqctXHobYs5OmKuKG2ry7FUQjp+L0Mt8tMEVWuMyZqR1lBl0F1XDMONNg77cwrg9rYt7Am9w2bOOP077rBOvjTZh8IyDQd8BW2oI4CJ5+zY1ZK2sZUaVOWHBA/L0fUQ="
  on:
    python: "3.3"
    tags: true
